model_name: 'FNO'
if_training: True
continue_training: False
batch_size: 20
unroll_step: 20
num_workers: 2
t_train: 21
model_update: 2
filename: '2D_CFD_M0.1_Eta0.01_Zeta0.01_periodic_128_Train.hdf5'
single_file: True
reduced_resolution: 2
reduced_resolution_t: 1
reduced_batch: 1
epochs: 500
learning_rate: 1.e-3

#FNO
num_channels: 4
modes: 12
width: 20
scheduler_step: 100
scheduler_gamma: 0.5
initial_step: 10


#####TempBalance
train_log_path: ##train_log_path
checkpoint_path: ###checkpoint_path
data_path: ###data_path
random_seed: 2024
weight_decay: 1.e-4
optimizer: 'Adam'
scheduler: 'StepLR'
temp_balance_lr: 'None'
fix_fingers: 'xmin_mid'
tb_metric: 'alpha'
lr_min_ratio: 0.6
lr_slope: 0.8
tb_interval_ep: 1
eigs_thres: 20
tb_batchnorm: 'True'
tb_hyperparam: 'lr'
task_id: '0'
exp_temp: 10